version: "3.0"

services:
  django:
    build: .
    container_name: django
    command: gunicorn --bind 0.0.0.0:8000 root.wsgi
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
  db:
    image: postgres:14.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=task
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432

  redis:
    image: redis:6-alpine
    container_name: redis
    volumes:
      - redis_data:/data/
    expose:
      - 6379


  nginx:
    build: ./nginx
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "80:80"
    depends_on:
      - django

volumes:
  static_volume:
  media_volume:
  redis_data:
  postgres_data:
